// Copyright (c) 2025-2026 Lexega LLC
// SPDX-License-Identifier: BUSL-1.1

//! Evidence construction utilities
//!
//! Shared utilities for building consistent evidence across all analyzers.

use crate::lexer::Span;

/// Line offset index for O(log n) line number lookups
///
/// Build once, use many times. Replaces O(n) scanning for each lookup.
pub struct LineIndex {
    /// Byte offsets where each line starts (0-indexed positions)
    line_starts: Vec<usize>,
}

/// Result of resolving a span to line numbers
#[derive(Debug, Clone)]
pub struct ResolvedLineInfo {
    /// Line number in the rendered SQL (always available)
    pub rendered_line: usize,
    /// Line number in the original template (if source map available)
    pub template_line: Option<usize>,
    /// Whether this line was generated by a macro
    pub is_generated: bool,
    /// Name of the macro that generated this line (if applicable)
    pub macro_name: Option<String>,
}

impl ResolvedLineInfo {
    /// Get the best line number to display to the user
    /// Prefers template_line if available, falls back to rendered_line
    pub fn display_line(&self) -> usize {
        self.template_line.unwrap_or(self.rendered_line)
    }
}

impl LineIndex {
    /// Build line index from source (O(n) - do once per file)
    pub fn new(src: &str) -> Self {
        let mut line_starts = vec![0];
        for (i, c) in src.char_indices() {
            if c == '\n' {
                line_starts.push(i + 1);
            }
        }
        Self { line_starts }
    }

    /// Get 1-indexed line number for a span (O(log n) via binary search)
    pub fn get_line_number(&self, span: Span) -> usize {
        let pos = span.start as usize;
        match self.line_starts.binary_search(&pos) {
            Ok(line) => line + 1, // Exact match at line start
            Err(line) => line,    // Between line starts, so in previous line
        }
    }

    /// Get 1-indexed column number for a span (O(log n) via binary search)
    /// Column is the offset from the start of the line
    pub fn get_column_number(&self, span: Span) -> usize {
        let pos = span.start as usize;
        let line_idx = match self.line_starts.binary_search(&pos) {
            Ok(line) => line,                    // Exact match at line start
            Err(line) => line.saturating_sub(1), // Between line starts
        };
        let line_start = self.line_starts.get(line_idx).copied().unwrap_or(0);
        pos.saturating_sub(line_start) + 1 // 1-indexed
    }

    /// CENTRALIZED LINE RESOLUTION: Resolve a span to full line info including template mapping
    ///
    /// This is THE canonical way to get line numbers for display. It handles:
    /// 1. Converting byte offset (span) to rendered line number
    /// 2. Looking up template line via source map (if available)
    /// 3. Determining if line was macro-generated
    ///
    /// Use `display_line()` on the result to get the best line for user display.
    pub fn resolve_span(
        &self,
        span: Span,
        source_map: Option<&crate::template::SourceMap>,
    ) -> ResolvedLineInfo {
        let rendered_line = self.get_line_number(span);

        let (template_line, is_generated, macro_name) = if let Some(sm) = source_map {
            match sm.get_line_source(rendered_line as u32) {
                Some(crate::template::LineSource::Literal { template_line }) => {
                    (Some(*template_line as usize), false, None)
                }
                Some(crate::template::LineSource::Generated {
                    call_site_line,
                    macro_name,
                }) => (Some(*call_site_line as usize), true, macro_name.clone()),
                Some(crate::template::LineSource::Unknown) | None => (None, false, None),
            }
        } else {
            (None, false, None)
        };

        ResolvedLineInfo {
            rendered_line,
            template_line,
            is_generated,
            macro_name,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::lexer::Span;

    #[test]
    fn test_line_index() {
        let src = "line 1\nline 2\nline 3";
        let index = LineIndex::new(src);

        // Test line 1 (positions 0-5)
        assert_eq!(index.get_line_number(Span { start: 0, end: 1 }), 1);
        assert_eq!(index.get_line_number(Span { start: 5, end: 6 }), 1);

        // Test line 2 (positions 7-12)
        assert_eq!(index.get_line_number(Span { start: 7, end: 8 }), 2);
        assert_eq!(index.get_line_number(Span { start: 12, end: 13 }), 2);

        // Test line 3 (positions 14+)
        assert_eq!(index.get_line_number(Span { start: 14, end: 15 }), 3);
        assert_eq!(index.get_line_number(Span { start: 19, end: 20 }), 3);
    }
}
