// Copyright (c) 2025-2026 Lexega LLC
// SPDX-License-Identifier: BUSL-1.1

/// Source of a line in the rendered SQL
#[derive(Debug, Clone)]
pub enum LineSource {
    /// Line comes directly from template literal SQL
    Literal { template_line: u32 },
    /// Line was generated by a macro/expression
    Generated {
        /// Line where the macro/expression was called in the template
        call_site_line: u32,
        /// Name of the macro that generated this (if known)
        macro_name: Option<String>,
    },
    /// Unknown source (e.g., from internal generation)
    Unknown,
}

impl LineSource {
    /// Check if this is generated content
    pub fn is_generated(&self) -> bool {
        matches!(self, LineSource::Generated { .. })
    }

    /// Get macro name if this was generated by a macro
    pub fn macro_name(&self) -> Option<&str> {
        match self {
            LineSource::Generated { macro_name, .. } => macro_name.as_deref(),
            _ => None,
        }
    }
}

/// Maps rendered SQL positions back to template positions
#[derive(Debug, Clone, Default)]
pub struct SourceMap {
    /// Maps rendered line number (1-indexed) to its source
    line_mappings: Vec<LineSource>,
}

impl SourceMap {
    pub fn new() -> Self {
        Self {
            line_mappings: Vec::new(),
        }
    }

    /// Record that the current output line corresponds to a template line (literal SQL)
    pub fn add_literal_mapping(&mut self, rendered_line: u32, template_line: u32) {
        self.ensure_capacity(rendered_line);
        if rendered_line > 0 {
            self.line_mappings[(rendered_line - 1) as usize] =
                LineSource::Literal { template_line };
        }
    }

    /// Record that the current output line was generated by a macro/expression
    pub fn add_generated_mapping(
        &mut self,
        rendered_line: u32,
        call_site_line: u32,
        macro_name: Option<String>,
    ) {
        self.ensure_capacity(rendered_line);
        if rendered_line > 0 {
            self.line_mappings[(rendered_line - 1) as usize] = LineSource::Generated {
                call_site_line,
                macro_name,
            };
        }
    }

    /// Add a mapping with an optional template line.
    pub fn add_line_mapping(&mut self, rendered_line: u32, template_line: Option<u32>) {
        self.ensure_capacity(rendered_line);
        if rendered_line > 0 {
            self.line_mappings[(rendered_line - 1) as usize] = match template_line {
                Some(line) => LineSource::Literal {
                    template_line: line,
                },
                None => LineSource::Unknown,
            };
        }
    }

    fn ensure_capacity(&mut self, rendered_line: u32) {
        while self.line_mappings.len() < rendered_line as usize {
            self.line_mappings.push(LineSource::Unknown);
        }
    }

    /// Get full source information for a rendered line
    pub fn get_line_source(&self, rendered_line: u32) -> Option<&LineSource> {
        if rendered_line == 0 || rendered_line as usize > self.line_mappings.len() {
            return None;
        }
        Some(&self.line_mappings[(rendered_line - 1) as usize])
    }

    /// Get statistics about mapping coverage
    pub fn stats(&self) -> SourceMapStats {
        let total_lines = self.line_mappings.len();
        let literal_lines = self
            .line_mappings
            .iter()
            .filter(|m| matches!(m, LineSource::Literal { .. }))
            .count();
        let generated_lines = self
            .line_mappings
            .iter()
            .filter(|m| matches!(m, LineSource::Generated { .. }))
            .count();

        SourceMapStats {
            total_rendered_lines: total_lines,
            template_mapped_lines: literal_lines,
            generated_lines,
            coverage_ratio: if total_lines > 0 {
                literal_lines as f32 / total_lines as f32
            } else {
                0.0
            },
        }
    }
}

#[derive(Debug, Clone)]
pub struct SourceMapStats {
    pub total_rendered_lines: usize,
    pub template_mapped_lines: usize,
    pub generated_lines: usize,
    pub coverage_ratio: f32,
}
