// Copyright (c) 2025-2026 Lexega LLC
// SPDX-License-Identifier: BUSL-1.1

//go:build ignore

// Command notices writes THIRD_PARTY_LICENSES.txt for the catalog extractors
// in the directories named on the command line, or for every extractor beside
// this file when none is named. A file lists the Go modules its extractor
// links on any release platform and carries the license and notice files
// those modules ship, along with Go's own license.
//
//	go run notices.go [extractor-dir ...]
package main

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

// platforms are the targets the extractors are released for.
var platforms = [][2]string{
	{"linux", "amd64"},
	{"linux", "arm64"},
	{"darwin", "amd64"},
	{"darwin", "arm64"},
	{"windows", "amd64"},
}

// noticePrefixes are the upper-cased name prefixes of the files a module
// ships its license terms and attributions in.
var noticePrefixes = []string{"LICENSE", "LICENCE", "COPYING", "NOTICE", "UNLICENSE"}

const rule = "================================================================================\n"

type module struct {
	path, version, dir string
}

func (m module) label() string { return m.path + " " + m.version }

// text is one license or notice text and everything that ships under it.
type text struct {
	file   string
	body   string
	usedBy []string
}

func main() {
	dirs := os.Args[1:]
	if len(dirs) == 0 {
		entries, err := os.ReadDir(".")
		if err != nil {
			fail(err)
		}
		for _, entry := range entries {
			if _, err := os.Stat(filepath.Join(entry.Name(), "go.mod")); err == nil {
				dirs = append(dirs, entry.Name())
			}
		}
	}
	for _, dir := range dirs {
		if err := write(dir); err != nil {
			fail(fmt.Errorf("%s: %w", dir, err))
		}
	}
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "Error:", err)
	os.Exit(1)
}

func write(dir string) error {
	modules, err := linkedModules(dir)
	if err != nil {
		return err
	}

	var texts []*text
	byBody := map[string]*text{}
	add := func(file, body, user string) {
		body = strings.TrimSpace(strings.ReplaceAll(body, "\r\n", "\n"))
		t, ok := byBody[body]
		if !ok {
			t = &text{file: file, body: body}
			byBody[body] = t
			texts = append(texts, t)
		}
		t.usedBy = append(t.usedBy, user)
	}

	goroot, err := goEnv(dir, "GOROOT")
	if err != nil {
		return err
	}
	goLicense, err := os.ReadFile(filepath.Join(goroot, "LICENSE"))
	if err != nil {
		return fmt.Errorf("Go's own license: %w", err)
	}
	add("LICENSE", string(goLicense), "the Go standard library and runtime")

	for _, m := range modules {
		files, err := noticeFiles(m.dir)
		if err != nil {
			return err
		}
		if len(files) == 0 {
			return fmt.Errorf("%s ships no license file in %s", m.label(), m.dir)
		}
		for _, file := range files {
			body, err := os.ReadFile(filepath.Join(m.dir, file))
			if err != nil {
				return err
			}
			add(file, string(body), m.label())
		}
	}

	var out bytes.Buffer
	out.WriteString(rule + "THIRD-PARTY LICENSES\n" + rule + "\n")
	fmt.Fprintf(&out, "This software (%s) includes the Go standard library and runtime", filepath.Base(dir))
	if len(modules) == 0 {
		out.WriteString("\nand no third-party Go module.\n")
	} else {
		out.WriteString("\nand the following third-party Go modules.\n")
	}
	out.WriteString("\nGenerated by notices.go from the modules the program links — do not edit manually.\n\n")
	for _, m := range modules {
		fmt.Fprintf(&out, "  %s\n", m.label())
	}
	for _, t := range texts {
		fmt.Fprintf(&out, "\n%s%s\n%sUsed by: %s\n\n%s\n", rule, t.file, rule, strings.Join(t.usedBy, ", "), t.body)
	}
	out.WriteString("\n" + rule + "END OF THIRD-PARTY LICENSES\n" + rule)

	return os.WriteFile(filepath.Join(dir, "THIRD_PARTY_LICENSES.txt"), out.Bytes(), 0o644)
}

// linkedModules lists the modules, other than the extractor's own, that
// provide a package to the extractor on at least one release platform.
func linkedModules(dir string) ([]module, error) {
	const format = `{{with .Module}}{{if not .Main}}{{.Path}}{{"\t"}}{{.Version}}{{"\t"}}{{.Dir}}{{end}}{{end}}`
	seen := map[string]module{}
	for _, platform := range platforms {
		cmd := exec.Command("go", "list", "-deps", "-f", format, ".")
		cmd.Dir = dir
		cmd.Env = append(os.Environ(), "GOOS="+platform[0], "GOARCH="+platform[1], "CGO_ENABLED=0")
		cmd.Stderr = os.Stderr
		listing, err := cmd.Output()
		if err != nil {
			return nil, fmt.Errorf("go list for %s/%s: %w", platform[0], platform[1], err)
		}
		for _, line := range strings.Split(string(listing), "\n") {
			fields := strings.Split(line, "\t")
			if len(fields) != 3 {
				continue
			}
			m := module{path: fields[0], version: fields[1], dir: fields[2]}
			seen[m.label()] = m
		}
	}
	modules := make([]module, 0, len(seen))
	for _, m := range seen {
		modules = append(modules, m)
	}
	sort.Slice(modules, func(i, j int) bool { return modules[i].label() < modules[j].label() })
	return modules, nil
}

// noticeFiles names the license and notice files at the root of a module.
func noticeFiles(dir string) ([]string, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}
	var files []string
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		name := strings.ToUpper(entry.Name())
		for _, prefix := range noticePrefixes {
			if strings.HasPrefix(name, prefix) {
				files = append(files, entry.Name())
				break
			}
		}
	}
	sort.Strings(files)
	return files, nil
}

func goEnv(dir, name string) (string, error) {
	cmd := exec.Command("go", "env", name)
	cmd.Dir = dir
	value, err := cmd.Output()
	if err != nil {
		return "", fmt.Errorf("go env %s: %w", name, err)
	}
	return strings.TrimSpace(string(value)), nil
}
